var MONTHS_SHORT = [ "jan", "feb", "mar", "apr", "may", "aug", "sep", "sept", "oct", "nov", "dec" ];
var MONTHS_LONG  = [ "january", "february", "march", "april", "may", "august", "september",
                     "october", "november", "december" ];
var MONTH_REGEXP = "(" + MONTHS_SHORT.join("|") + "|" + MONTHS_LONG.join("|") + ")";

var TIME = /(\d{1,2})[.:,]?(\d{0,2})\s*(a|p)?\.?m?\.?/;
var DATE_ONE = /\d\d[-,.\/]\d\d[-,.\/]\d\d(\d\d)?/;
var DATE_TWO = new RegExp(MONTH_REGEXP + '[,\s]\s*\d{1,2}(st|nd|rd|th)([,\s]\s*\d\d\d\d)?');
var DATE_THREE = new RegExp('[,\s]\s*\d{1,2}(st|nd|rd|th)' + MONTH_REGEXP + '([,\s]\s*\d\d\d\d)?');

var cities = {
    "Aba":"Africa/Lagos",
    "Abeokuta":"Africa/Lagos",
    "Abidjan":"Africa/Abidjan",
    "Abobo":"Africa/Abidjan",
    "Abomey-Calavi":"Africa/Porto-Novo",
    "Abu Dhabi":"Asia/Dubai",
    "Abu Ghurayb":"Asia/Baghdad",
    "Abuja":"Africa/Lagos",
    "Acapulco de Juarez":"America/Mexico_City",
    "Accra":"Africa/Accra",
    "Ad Dammam":"Asia/Riyadh",
    "Adamstown":"Pacific/Pitcairn",
    "Adana":"Europe/Istanbul",
    "Addis Ababa":"Africa/Addis_Ababa",
    "Adelaide":"Australia/Adelaide",
    "Afghanistan":"Asia/Kabul",
    "Agadir":"Africa/Casablanca",
    "Agra":"Asia/Kolkata",
    "Aguascalientes":"America/Mexico_City",
    "Ahmadabad":"Asia/Kolkata",
    "Ahvaz":"Asia/Tehran",
    "Ajmer":"Asia/Kolkata",
    "Akola":"Asia/Kolkata",
    "Akure":"Africa/Lagos",
    "Al Basrah":"Asia/Baghdad",
    "Al Basrah al Qadimah":"Asia/Baghdad",
    "Al Hudaydah":"Asia/Aden",
    "Al Jizah":"Africa/Cairo",
    "Al Mahallah al Kubra":"Africa/Cairo",
    "Al Mansurah":"Africa/Cairo",
    "Al Mawsil al Jadidah":"Asia/Baghdad",
    "Al Ubayyid":"Africa/Khartoum",
    "Al `Ayn":"Asia/Dubai",
    "Alabama":"America/Chicago",
    "Aland Islands":"Europe/Helsinki",
    "Alaska":"America/Juneau",
    "Albania":"Europe/Tirane",
    "Albuquerque":"America/Denver",
    "Aleppo":"Asia/Damascus",
    "Alexandria":"Africa/Cairo",
    "Algeria":"Africa/Algiers",
    "Algiers":"Africa/Algiers",
    "Aligarh":"Asia/Kolkata",
    "Allahabad":"Asia/Kolkata",
    "Almaty":"Asia/Almaty",
    "Alofi":"Pacific/Niue",
    "Amagasaki":"Asia/Tokyo",
    "American Samoa":"Pacific/Pago_Pago",
    "Amman":"Asia/Amman",
    "Amravati":"Asia/Kolkata",
    "Amritsar":"Asia/Kolkata",
    "Amsterdam":"Europe/Amsterdam",
    "An Najaf":"Asia/Baghdad",
    "An Nasiriyah":"Asia/Baghdad",
    "Ananindeua":"America/Santarem",
    "Anchorage":"America/Juneau",
    "Andorra":"Europe/Andorra",
    "Andorra la Vella":"Europe/Andorra",
    "Angola":"Africa/Luanda",
    "Anguilla":"America/Anguilla",
    "Ankara":"Europe/Istanbul",
    "Ansan":"Asia/Seoul",
    "Anshan":"Asia/Harbin",
    "Antalya":"Europe/Istanbul",
    "Antananarivo":"Indian/Antananarivo",
    "Antarctica":"Antarctica/South_Pole",
    "Antigua and Barbuda":"America/Antigua",
    "Antipolo":"Asia/Manila",
    "Antwerp":"Europe/Brussels",
    "Aomen":"Asia/Macau",
    "Apia":"Pacific/Apia",
    "Aracaju":"America/Maceio",
    "Arak":"Asia/Tehran",
    "Arbil":"Asia/Baghdad",
    "Ardabil":"Asia/Tehran",
    "Arequipa":"America/Lima",
    "Arizona":"America/Phoenix",
    "Arkansas":"America/Chicago",
    "Armenia":"Asia/Yerevan",
    "Aruba":"America/Aruba",
    "As Sulaymaniyah":"Asia/Baghdad",
    "Asansol":"Asia/Kolkata",
    "Ashgabat":"Asia/Ashgabat",
    "Asmara":"Africa/Asmara",
    "Astana":"Asia/Qyzylorda",
    "Astrakhan'":"Europe/Volgograd",
    "Asuncion":"America/Asuncion",
    "Asyut":"Africa/Cairo",
    "At Ta'if":"Asia/Riyadh",
    "Athens":"Europe/Athens",
    "Atlanta":"America/New_York",
    "Auckland":"Pacific/Auckland",
    "Aurangabad":"Asia/Kolkata",
    "Austin":"America/Chicago",
    "Austria":"Europe/Vienna",
    "Avarua":"Pacific/Rarotonga",
    "Az Zarqa'":"Asia/Amman",
    "Azadshahr":"Asia/Tehran",
    "Azerbaijan":"Asia/Baku",
    "Baghdad":"Asia/Baghdad",
    "Bahamas":"America/Nassau",
    "Bahawalpur":"Asia/Karachi",
    "Bahrain":"Asia/Bahrain",
    "Bairiki":"Pacific/Tarawa",
    "Baku":"Asia/Baku",
    "Balikpapan":"Asia/Makassar",
    "Baltimore":"America/New_York",
    "Bamako":"Africa/Bamako",
    "Bamenda":"Africa/Douala",
    "Bandar Seri Begawan":"Asia/Brunei",
    "Bandung":"Asia/Jakarta",
    "Banghazi":"Africa/Tripoli",
    "Bangkok":"Asia/Bangkok",
    "Bangladesh":"Asia/Dhaka",
    "Bangui":"Africa/Bangui",
    "Banjarmasin":"Asia/Makassar",
    "Banjul":"Africa/Banjul",
    "Baoding":"Asia/Shanghai",
    "Baotou":"Asia/Chongqing",
    "Barbados":"America/Barbados",
    "Bareilly":"Asia/Kolkata",
    "Barnaul":"Asia/Omsk",
    "Barquisimeto":"America/Caracas",
    "Barranquilla":"America/Bogota",
    "Basse-Terre":"America/Guadeloupe",
    "Basseterre":"America/St_Kitts",
    "Beijing":"Asia/Harbin",
    "Beira":"Africa/Maputo",
    "Beirut":"Asia/Beirut",
    "Bekasi":"Asia/Jakarta",
    "Belarus":"Europe/Minsk",
    "Belem":"America/Belem",
    "Belford Roxo":"America/Sao_Paulo",
    "Belgaum":"Asia/Kolkata",
    "Belgium":"Europe/Brussels",
    "Belgrade":"Europe/Belgrade",
    "Belize":"America/Belize",
    "Bello":"America/Bogota",
    "Belmopan":"America/Belize",
    "Belo Horizonte":"America/Sao_Paulo",
    "Benares":"Asia/Kolkata",
    "Bengaluru":"Asia/Kolkata",
    "Bengbu":"Asia/Shanghai",
    "Benin":"Africa/Porto-Novo",
    "Benin-City":"Africa/Lagos",
    "Benoni":"Africa/Johannesburg",
    "Benxi":"Asia/Harbin",
    "Berlin":"Europe/Berlin",
    "Bermuda":"Atlantic/Bermuda",
    "Bern":"Europe/Zurich",
    "Betim":"America/Sao_Paulo",
    "Bhatpara":"Asia/Kolkata",
    "Bhavnagar":"Asia/Kolkata",
    "Bhilai":"Asia/Kolkata",
    "Bhiwandi":"Asia/Kolkata",
    "Bhopal":"Asia/Kolkata",
    "Bhubaneshwar":"Asia/Kolkata",
    "Bhutan":"Asia/Thimphu",
    "Bien Hoa":"Asia/Ho_Chi_Minh",
    "Bikaner":"Asia/Kolkata",
    "Billings":"America/Denver",
    "Bishkek":"Asia/Bishkek",
    "Bissau":"Africa/Bissau",
    "Blantyre":"Africa/Blantyre",
    "Bloemfontein":"Africa/Johannesburg",
    "Bochum":"Europe/Berlin",
    "Bochum-Hordel":"Europe/Berlin",
    "Bogor":"Asia/Jakarta",
    "Bogota":"America/Bogota",
    "Boise":"America/Boise",
    "Bokaro":"Asia/Kolkata",
    "Boksburg":"Africa/Johannesburg",
    "Bolivia":"America/La_Paz",
    "Bologna":"Europe/Rome",
    "Bosnia and Herzegovina":"Europe/Sarajevo",
    "Boston":"America/New_York",
    "Botswana":"Africa/Gaborone",
    "Bouake":"Africa/Abidjan",
    "Boumerdas":"Africa/Algiers",
    "Bouvet Island":"Europe/Oslo",
    "Brasilia":"America/Sao_Paulo",
    "Bratislava":"Europe/Bratislava",
    "Brazzaville":"Africa/Brazzaville",
    "Bremen":"Europe/Berlin",
    "Bridgeport":"America/New_York",
    "Bridgetown":"America/Barbados",
    "Brisbane":"Australia/Brisbane",
    "Bristol":"Europe/London",
    "British Indian Ocean Territory":"Indian/Chagos",
    "British Virgin Islands":"America/Tortola",
    "Brooklyn":"America/New_York",
    "Brunei":"Asia/Brunei",
    "Brussels":"Europe/Brussels",
    "Bryansk":"Europe/Moscow",
    "Bucaramanga":"America/Bogota",
    "Bucuresti":"Europe/Bucharest",
    "Budapest":"Europe/Budapest",
    "Buenos Aires":"America/Argentina/Buenos_Aires",
    "Bujumbura":"Africa/Bujumbura",
    "Bulawayo":"Africa/Harare",
    "Bulgaria":"Europe/Sofia",
    "Bur Sa`id":"Africa/Cairo",
    "Buraydah":"Asia/Riyadh",
    "Burkina Faso":"Africa/Ouagadougou",
    "Burlington":"America/New_York",
    "Bursa":"Europe/Istanbul",
    "Burundi":"Africa/Bujumbura",
    "CT (Central Time)":"America/Chicago",
    "Cagayan de Oro":"Asia/Manila",
    "Cairo":"Africa/Cairo",
    "Calabar":"Africa/Lagos",
    "Calcutta":"Asia/Kolkata",
    "Calgary":"America/Edmonton",
    "Cali":"America/Bogota",
    "Calicut":"Asia/Kolkata",
    "California":"America/Los_Angeles",
    "Callao":"America/Lima",
    "Camayenne":"Africa/Conakry",
    "Cambodia":"Asia/Phnom_Penh",
    "Cameroon":"Africa/Douala",
    "Campinas":"America/Sao_Paulo",
    "Campo Grande":"America/Campo_Grande",
    "Campos":"America/Sao_Paulo",
    "Canberra":"Australia/Sydney",
    "Cancun":"America/Cancun",
    "Cangzhou":"Asia/Shanghai",
    "Cankaya":"Europe/Istanbul",
    "Cape Town":"Africa/Johannesburg",
    "Cape Verde":"Atlantic/Cape_Verde",
    "Caracas":"America/Caracas",
    "Carrefour":"America/Port-au-Prince",
    "Cartagena":"America/Bogota",
    "Casablanca":"Africa/Casablanca",
    "Castries":"America/St_Lucia",
    "Caxias do Sul":"America/Sao_Paulo",
    "Cayenne":"America/Cayenne",
    "Cayman Islands":"America/Cayman",
    "Cebu City":"Asia/Manila",
    "Central African Republic":"Africa/Bangui",
    "Central Time (CT)":"America/Chicago",
    "Ch'angwon":"Asia/Seoul",
    "Ch'ongju":"Asia/Seoul",
    "Chad":"Africa/Ndjamena",
    "Chandigarh":"Asia/Kolkata",
    "Changchun":"Asia/Harbin",
    "Changde":"Asia/Chongqing",
    "Changsha":"Asia/Chongqing",
    "Changzhi":"Asia/Chongqing",
    "Changzhou":"Asia/Shanghai",
    "Chaoyang":"Asia/Harbin",
    "Chaozhou":"Asia/Shanghai",
    "Charleston":"America/New_York",
    "Charlotte":"America/New_York",
    "Cheboksary":"Europe/Moscow",
    "Cheju":"Asia/Seoul",
    "Chelyabinsk":"Asia/Yekaterinburg",
    "Chengde":"Asia/Harbin",
    "Chengdu":"Asia/Chongqing",
    "Chennai":"Asia/Kolkata",
    "Cheyenne":"America/Denver",
    "Chi-lung":"Asia/Taipei",
    "Chiba":"Asia/Tokyo",
    "Chicago":"America/Chicago",
    "Chiclayo":"America/Lima",
    "Chihuahua":"America/Chihuahua",
    "Chile":"America/Santiago",
    "China":"Asia/Chongqing",
    "Chisinau":"Europe/Chisinau",
    "Chittagong":"Asia/Dhaka",
    "Chongqing":"Asia/Chongqing",
    "Chonju":"Asia/Seoul",
    "Christchurch":"Pacific/Auckland",
    "Christmas Island":"Indian/Christmas",
    "Cimahi":"Asia/Jakarta",
    "Ciudad Guayana":"America/Caracas",
    "Ciudad Juarez":"America/Chihuahua",
    "Ciudad Lopez Mateos":"America/Mexico_City",
    "Ciudad Nezahualcoyotl":"America/Mexico_City",
    "Cleveland":"America/New_York",
    "Cochabamba":"America/La_Paz",
    "Cochin":"Asia/Kolkata",
    "Cocos Islands":"Indian/Cocos",
    "Coimbatore":"Asia/Kolkata",
    "Colombia":"America/Bogota",
    "Colombo":"Asia/Colombo",
    "Colorado":"America/Denver",
    "Columbia":"America/New_York",
    "Columbus":"America/New_York",
    "Comilla":"Asia/Dhaka",
    "Comoros":"Indian/Comoro",
    "Conakry":"Africa/Conakry",
    "Connecticut":"America/New_York",
    "Constantine":"Africa/Algiers",
    "Contagem":"America/Sao_Paulo",
    "Cook Islands":"Pacific/Rarotonga",
    "Copenhagen":"Europe/Copenhagen",
    "Cordoba":"America/Argentina/Cordoba",
    "Costa Rica":"America/Costa_Rica",
    "Cotonou":"Africa/Porto-Novo",
    "Croatia":"Europe/Zagreb",
    "Cuautitlan Izcalli":"America/Mexico_City",
    "Cuba":"America/Havana",
    "Cucuta":"America/Bogota",
    "Cuiaba":"America/Cuiaba",
    "Culiacan":"America/Mazatlan",
    "Curitiba":"America/Sao_Paulo",
    "Cuttack":"Asia/Kolkata",
    "Cyprus":"Asia/Nicosia",
    "Czech Republic":"Europe/Prague",
    "Da Nang":"Asia/Ho_Chi_Minh",
    "Dakar":"Africa/Dakar",
    "Dalian":"Asia/Shanghai",
    "Dallas":"America/Chicago",
    "Damascus":"Asia/Damascus",
    "Dandong":"Asia/Harbin",
    "Dar es Salaam":"Africa/Dar_es_Salaam",
    "Dasmarinas":"Asia/Manila",
    "Datong":"Asia/Shanghai",
    "Davao":"Asia/Manila",
    "Dayan":"Asia/Chongqing",
    "Dehra Dun":"Asia/Kolkata",
    "Delaware":"America/New_York",
    "Delhi":"Asia/Kolkata",
    "Delmas 73":"America/Port-au-Prince",
    "Democratic Republic of the Congo":"Africa/Lubumbashi",
    "Den Haag":"Europe/Amsterdam",
    "Denmark":"Europe/Copenhagen",
    "Denpasar":"Asia/Makassar",
    "Denver":"America/Denver",
    "Depok":"Asia/Jakarta",
    "Des Moines":"America/Chicago",
    "Detroit":"America/Detroit",
    "Dezhou":"Asia/Shanghai",
    "Dhaka":"Asia/Dhaka",
    "Diadema":"America/Sao_Paulo",
    "Dili":"Asia/Dili",
    "Diyarbakir":"Europe/Istanbul",
    "Djibouti":"Africa/Djibouti",
    "Dnipropetrovsk":"Europe/Zaporozhye",
    "Dodoma":"Africa/Dar_es_Salaam",
    "Doha":"Asia/Qatar",
    "Dominica":"America/Dominica",
    "Dominican Republic":"America/Santo_Domingo",
    "Donets'k":"Europe/Zaporozhye",
    "Dongguan":"Asia/Chongqing",
    "Dortmund":"Europe/Berlin",
    "Douala":"Africa/Douala",
    "Douglas":"Europe/Isle_of_Man",
    "Dresden":"Europe/Berlin",
    "Dubai":"Asia/Dubai",
    "Dublin":"Europe/Dublin",
    "Duisburg":"Europe/Berlin",
    "Duque de Caxias":"America/Sao_Paulo",
    "Durango":"America/Monterrey",
    "Durban":"Africa/Johannesburg",
    "Durgapur":"Asia/Kolkata",
    "Dushanbe":"Asia/Dushanbe",
    "Dusseldorf":"Europe/Berlin",
    "ET (Eastern Time)":"America/New_York",
    "East Timor":"Asia/Dili",
    "Eastern Time (ET)":"America/New_York",
    "Ecatepec":"America/Mexico_City",
    "Ecuador":"America/Guayaquil",
    "Edinburgh":"Europe/London",
    "Edmonton":"America/Edmonton",
    "Egypt":"Africa/Cairo",
    "El Paso":"America/Denver",
    "El Salvador":"America/El_Salvador",
    "England":"Europe/London",
    "Enugu":"Africa/Lagos",
    "Equatorial Guinea":"Africa/Malabo",
    "Eritrea":"Africa/Asmara",
    "Erzurum":"Europe/Istanbul",
    "Esfahan":"Asia/Tehran",
    "Eskisehir":"Europe/Istanbul",
    "Essen":"Europe/Berlin",
    "Estonia":"Europe/Tallinn",
    "Ethiopia":"Africa/Addis_Ababa",
    "Faisalabad":"Asia/Karachi",
    "Falkland Islands":"Atlantic/Stanley",
    "Fargo":"America/Chicago",
    "Faridabad":"Asia/Kolkata",
    "Faroe Islands":"Atlantic/Faroe",
    "Feira de Santana":"America/Bahia",
    "Fes":"Africa/Casablanca",
    "Fiji":"Pacific/Fiji",
    "Finland":"Europe/Helsinki",
    "Florence":"Europe/Rome",
    "Florianopolis":"America/Sao_Paulo",
    "Florida - Miami":"America/New_York",
    "Florida - Pensacola":"America/Chicago",
    "Flying Fish Cove":"Indian/Christmas",
    "Fort Worth":"America/Chicago",
    "Fort-de-France":"America/Martinique",
    "Fortaleza":"America/Fortaleza",
    "Foshan":"Asia/Chongqing",
    "France":"Europe/Paris",
    "Frankfurt am Main":"Europe/Berlin",
    "Freetown":"Africa/Freetown",
    "French Guiana":"America/Cayenne",
    "French Polynesia":"Pacific/Marquesas",
    "French Southern Territories":"Indian/Kerguelen",
    "Fresno":"America/Los_Angeles",
    "Fujisawa":"Asia/Tokyo",
    "Fukuoka":"Asia/Tokyo",
    "Fukuyama":"Asia/Tokyo",
    "Funabashi":"Asia/Tokyo",
    "Funafuti":"Pacific/Funafuti",
    "Fushun":"Asia/Harbin",
    "Fuxin":"Asia/Harbin",
    "Fuzhou":"Asia/Shanghai",
    "Gabon":"Africa/Libreville",
    "Gaborone":"Africa/Gaborone",
    "Gambia":"Africa/Banjul",
    "Garoua":"Africa/Douala",
    "Gaya":"Asia/Kolkata",
    "Gaza":"Asia/Gaza",
    "Gaziantep":"Europe/Istanbul",
    "Gdansk":"Europe/Warsaw",
    "Genova":"Europe/Rome",
    "George Town":"America/Cayman",
    "Georgetown":"America/Guyana",
    "Germany":"Europe/Berlin",
    "Ghana":"Africa/Accra",
    "Ghaziabad":"Asia/Kolkata",
    "Gibraltar":"Europe/Gibraltar",
    "Gifu":"Asia/Tokyo",
    "Glasgow":"Europe/London",
    "Goeteborg":"Europe/Stockholm",
    "Goiania":"America/Sao_Paulo",
    "Gold Coast":"Australia/Brisbane",
    "Grand Dakar":"Africa/Dakar",
    "Grand Turk":"America/Grand_Turk",
    "Great Britain":"Europe/London",
    "Greece":"Europe/Athens",
    "Grenada":"America/Grenada",
    "Grytviken":"Atlantic/South_Georgia",
    "Guadalajara":"America/Mexico_City",
    "Guadalupe":"America/Monterrey",
    "Guadeloupe":"America/Guadeloupe",
    "Guam":"Pacific/Guam",
    "Guangzhou":"Asia/Chongqing",
    "Guarulhos":"America/Sao_Paulo",
    "Guatemala":"America/Guatemala",
    "Guatemala City":"America/Guatemala",
    "Guayaquil":"America/Guayaquil",
    "Guernsey":"Europe/Guernsey",
    "Guilin":"Asia/Chongqing",
    "Guinea":"Africa/Conakry",
    "Guinea-Bissau":"Africa/Bissau",
    "Guiyang":"Asia/Chongqing",
    "Gujranwala":"Asia/Karachi",
    "Gulbarga":"Asia/Kolkata",
    "Guli":"Asia/Shanghai",
    "Guntur":"Asia/Kolkata",
    "Gustavia":"America/Guadeloupe",
    "Guwahati":"Asia/Kolkata",
    "Guyana":"America/Guyana",
    "Gwalior":"Asia/Kolkata",
    "Ha Noi":"Asia/Ho_Chi_Minh",
    "Hachioji":"Asia/Tokyo",
    "Hagatna":"Pacific/Guam",
    "Haikou":"Asia/Chongqing",
    "Haiphong":"Asia/Ho_Chi_Minh",
    "Haiti":"America/Port-au-Prince",
    "Hamadan":"Asia/Tehran",
    "Hamah":"Asia/Damascus",
    "Hamamatsu":"Asia/Tokyo",
    "Hamburg":"Europe/Berlin",
    "Hamhung":"Asia/Pyongyang",
    "Hamilton":"America/Toronto",
    "Handan":"Asia/Shanghai",
    "Hangzhou":"Asia/Shanghai",
    "Hannover":"Europe/Berlin",
    "Haora":"Asia/Kolkata",
    "Harare":"Africa/Harare",
    "Harbin":"Asia/Harbin",
    "Hargeysa":"Africa/Mogadishu",
    "Havana":"America/Havana",
    "Hawaii":"Pacific/Honolulu",
    "Heard Island and McDonald Islands":"Australia/Perth",
    "Hefei":"Asia/Shanghai",
    "Hegang":"Asia/Harbin",
    "Helsinki":"Europe/Helsinki",
    "Hengshui":"Asia/Shanghai",
    "Hengyang":"Asia/Chongqing",
    "Hermosillo":"America/Hermosillo",
    "Himeji":"Asia/Tokyo",
    "Hims":"Asia/Damascus",
    "Hirakata":"Asia/Tokyo",
    "Hiroshima":"Asia/Tokyo",
    "Hohhot":"Asia/Chongqing",
    "Homyel'":"Europe/Minsk",
    "Honduras":"America/Tegucigalpa",
    "Hong Kong":"Asia/Hong_Kong",
    "Honiara":"Pacific/Guadalcanal",
    "Honolulu":"Pacific/Honolulu",
    "Houston":"America/Chicago",
    "Hsin-chu-shih":"Asia/Taipei",
    "Huaibei":"Asia/Shanghai",
    "Huainan":"Asia/Shanghai",
    "Huaiyin":"Asia/Shanghai",
    "Huancayo":"America/Lima",
    "Huangshi":"Asia/Shanghai",
    "Hubli":"Asia/Kolkata",
    "Hungary":"Europe/Budapest",
    "Ibadan":"Africa/Lagos",
    "Ibague":"America/Bogota",
    "Iceland":"Atlantic/Reykjavik",
    "Ichikawa":"Asia/Tokyo",
    "Idaho - Boise":"America/Boise",
    "Illinois":"America/Chicago",
    "Iloilo":"Asia/Manila",
    "Ilorin":"Africa/Lagos",
    "Inch'on":"Asia/Seoul",
    "India":"Asia/Kolkata",
    "Indiana - Indianapolis":"America/Indiana/Indianapolis",
    "Indianapolis":"America/Indiana/Indianapolis",
    "Indonesia":"Asia/Makassar",
    "Indore":"Asia/Kolkata",
    "Iowa":"America/Chicago",
    "Ipoh":"Asia/Kuala_Lumpur",
    "Iquitos":"America/Lima",
    "Iran":"Asia/Tehran",
    "Iraq":"Asia/Baghdad",
    "Ireland":"Europe/Dublin",
    "Irkutsk":"Asia/Irkutsk",
    "Islamabad":"Asia/Karachi",
    "Isle of Man":"Europe/Isle_of_Man",
    "Israel":"Asia/Jerusalem",
    "Istanbul":"Europe/Istanbul",
    "Italy":"Europe/Rome",
    "Ivanovo":"Europe/Moscow",
    "Ivory Coast":"Africa/Abidjan",
    "Izhevsk":"Europe/Samara",
    "Izmir":"Europe/Istanbul",
    "Jabalpur":"Asia/Kolkata",
    "Jaboatao":"America/Recife",
    "Jaboatao dos Guararapes":"America/Recife",
    "Jackson":"America/Chicago",
    "Jacksonville":"America/New_York",
    "Jaipur":"Asia/Kolkata",
    "Jakarta":"Asia/Jakarta",
    "Jalandhar":"Asia/Kolkata",
    "Jalapa Enriquez":"America/Mexico_City",
    "Jalgaon":"Asia/Kolkata",
    "Jamaica":"America/Jamaica",
    "Jambi":"Asia/Jakarta",
    "Jamestown":"Atlantic/St_Helena",
    "Jammu":"Asia/Kolkata",
    "Jamnagar":"Asia/Kolkata",
    "Jamshedpur":"Asia/Kolkata",
    "Japan":"Asia/Tokyo",
    "Jersey":"Europe/Jersey",
    "Jerusalem":"Asia/Jerusalem",
    "Jhansi":"Asia/Kolkata",
    "Jiamusi":"Asia/Harbin",
    "Jiangmen":"Asia/Chongqing",
    "Jiaojiang":"Asia/Shanghai",
    "Jiaozuo":"Asia/Shanghai",
    "Jiaxing":"Asia/Shanghai",
    "Jiddah":"Asia/Riyadh",
    "Jieyang":"Asia/Shanghai",
    "Jilin":"Asia/Harbin",
    "Jinan":"Asia/Shanghai",
    "Jining":"Asia/Shanghai",
    "Jinzhou":"Asia/Harbin",
    "Jixi":"Asia/Harbin",
    "Joao Pessoa":"America/Fortaleza",
    "Jodhpur":"Asia/Kolkata",
    "Johannesburg":"Africa/Johannesburg",
    "Johor Bahru":"Asia/Kuala_Lumpur",
    "Joinville":"America/Sao_Paulo",
    "Jordan":"Asia/Amman",
    "Jos":"Africa/Lagos",
    "Juan Dolio":"America/Santo_Domingo",
    "Juiz de Fora":"America/Sao_Paulo",
    "Kabul":"Asia/Kabul",
    "Kaduna":"Africa/Lagos",
    "Kagoshima":"Asia/Tokyo",
    "Kahramanmaras":"Europe/Istanbul",
    "Kahriz":"Asia/Tehran",
    "Kaifeng":"Asia/Shanghai",
    "Kaliningrad":"Europe/Kaliningrad",
    "Kalyan":"Asia/Kolkata",
    "Kampala":"Africa/Kampala",
    "Kampung Baru Subang":"Asia/Kuala_Lumpur",
    "Kananga":"Africa/Lubumbashi",
    "Kanazawa":"Asia/Tokyo",
    "Kandahar":"Asia/Kabul",
    "Kano":"Africa/Lagos",
    "Kanpur":"Asia/Kolkata",
    "Kansas - Wichita":"America/Chicago",
    "Kansas City":"America/Chicago",
    "Kao-hsiung":"Asia/Taipei",
    "Karachi":"Asia/Karachi",
    "Karagandy":"Asia/Aqtobe",
    "Karaj":"Asia/Tehran",
    "Karbala'":"Asia/Baghdad",
    "Kassala":"Africa/Khartoum",
    "Kathmandu":"Asia/Kathmandu",
    "Katsina":"Africa/Lagos",
    "Kaunas":"Europe/Vilnius",
    "Kawaguchi":"Asia/Tokyo",
    "Kawasaki":"Asia/Tokyo",
    "Kayseri":"Europe/Istanbul",
    "Kazan'":"Europe/Moscow",
    "Kemerovo":"Asia/Krasnoyarsk",
    "Kentucky - Lexington":"America/New_York",
    "Kentucky - Lexington-Fayette":"America/New_York",
    "Kentucky - Louisville":"America/Kentucky/Louisville",
    "Kentucky - Owensboro":"America/Chicago",
    "Kenya":"Africa/Nairobi",
    "Kerman":"Asia/Tehran",
    "Kermanshah":"Asia/Tehran",
    "Khabarovsk":"Asia/Vladivostok",
    "Khabarovsk Vtoroy":"Asia/Vladivostok",
    "Khamis Mushayt":"Asia/Riyadh",
    "Kharkiv":"Europe/Zaporozhye",
    "Khartoum":"Africa/Khartoum",
    "Khmel'nyts'kyy":"Europe/Kiev",
    "Khulna":"Asia/Dhaka",
    "Kiev":"Europe/Kiev",
    "Kigali":"Africa/Kigali",
    "Kingston":"America/Jamaica",
    "Kingstown":"America/St_Vincent",
    "Kinshasa":"Africa/Kinshasa",
    "Kirkuk":"Asia/Baghdad",
    "Kirov":"Europe/Volgograd",
    "Kisangani":"Africa/Lubumbashi",
    "Kitakyushu":"Asia/Tokyo",
    "Kitchener":"America/Toronto",
    "Kitwe":"Africa/Lusaka",
    "Klang":"Asia/Kuala_Lumpur",
    "Knoxville":"America/New_York",
    "Kobe":"Asia/Tokyo",
    "Koeln":"Europe/Berlin",
    "Kolhapur":"Asia/Kolkata",
    "Kolwezi":"Africa/Lubumbashi",
    "Konya":"Europe/Istanbul",
    "Korba":"Asia/Kolkata",
    "Koror":"Pacific/Palau",
    "Kota":"Asia/Kolkata",
    "Kota Kinabalu":"Asia/Kuching",
    "Kotli":"Asia/Karachi",
    "Kousseri":"Africa/Douala",
    "Kowloon":"Asia/Hong_Kong",
    "Krakow":"Europe/Warsaw",
    "Krasnodar":"Europe/Moscow",
    "Krasnoyarsk":"Asia/Krasnoyarsk",
    "Krugersdorp":"Africa/Johannesburg",
    "Kryvyy Rih":"Europe/Zaporozhye",
    "Kuala Lumpur":"Asia/Kuala_Lumpur",
    "Kuching":"Asia/Kuching",
    "Kumamoto":"Asia/Tokyo",
    "Kumasi":"Africa/Accra",
    "Kunming":"Asia/Chongqing",
    "Kurashiki":"Asia/Tokyo",
    "Kursk":"Europe/Moscow",
    "Kuwait":"Asia/Kuwait",
    "Kwangju":"Asia/Seoul",
    "Kyoto":"Asia/Tokyo",
    "Kyrgyzstan":"Asia/Bishkek",
    "L'viv":"Europe/Uzhgorod",
    "La Paz":"America/La_Paz",
    "La Plata":"America/Argentina/Buenos_Aires",
    "Lagos":"Africa/Lagos",
    "Lahore":"Asia/Karachi",
    "Langfang":"Asia/Shanghai",
    "Lanzhou":"Asia/Chongqing",
    "Laos":"Asia/Vientiane",
    "Las Palmas de Gran Canaria":"Atlantic/Canary",
    "Las Pavas":"America/Bogota",
    "Las Vegas":"America/Los_Angeles",
    "Latvia":"Europe/Riga",
    "Lebanon":"Asia/Beirut",
    "Leeds":"Europe/London",
    "Leipzig":"Europe/Berlin",
    "Leon":"America/Mexico_City",
    "Lesotho":"Africa/Maseru",
    "Lexington":"America/New_York",
    "Lexington-Fayette":"America/New_York",
    "Liaoyang":"Asia/Harbin",
    "Liaoyuan":"Asia/Harbin",
    "Liberia":"Africa/Monrovia",
    "Libreville":"Africa/Libreville",
    "Libya":"Africa/Tripoli",
    "Liechtenstein":"Europe/Vaduz",
    "Likasi":"Africa/Lubumbashi",
    "Lilongwe":"Africa/Blantyre",
    "Lima":"America/Lima",
    "Lincoln":"America/Chicago",
    "Lipetsk":"Europe/Moscow",
    "Lisbon":"Europe/Lisbon",
    "Lithuania":"Europe/Vilnius",
    "Little Rock":"America/Chicago",
    "Liuyang":"Asia/Chongqing",
    "Liverpool":"Europe/London",
    "Ljubljana":"Europe/Ljubljana",
    "Lobamba":"Africa/Mbabane",
    "Lodz":"Europe/Warsaw",
    "Lome":"Africa/Lome",
    "London":"Europe/London",
    "Londrina":"America/Sao_Paulo",
    "Long Beach":"America/Los_Angeles",
    "Longyearbyen":"Arctic/Longyearbyen",
    "Los Angeles":"America/Los_Angeles",
    "Louisiana":"America/Chicago",
    "Louisville":"America/Kentucky/Louisville",
    "Luancheng":"Asia/Shanghai",
    "Luanda":"Africa/Luanda",
    "Lubumbashi":"Africa/Lubumbashi",
    "Lucknow":"Asia/Kolkata",
    "Ludhiana":"Asia/Kolkata",
    "Luhans'k":"Europe/Zaporozhye",
    "Luohe":"Asia/Shanghai",
    "Luoyang":"Asia/Chongqing",
    "Luqiaozhen":"Asia/Shanghai",
    "Lusaka":"Africa/Lusaka",
    "Luxembourg":"Europe/Luxembourg",
    "Luxor":"Africa/Cairo",
    "Lyon":"Europe/Paris",
    "MT (Mountain Time)":"America/Denver",
    "Macao":"Asia/Macau",
    "Macedonia":"Europe/Skopje",
    "Maceio":"America/Maceio",
    "Machida":"Asia/Tokyo",
    "Madagascar":"Indian/Antananarivo",
    "Madrid":"Europe/Madrid",
    "Madurai":"Asia/Kolkata",
    "Magnitogorsk":"Asia/Yekaterinburg",
    "Maiduguri":"Africa/Lagos",
    "Maine":"America/New_York",
    "Majuro":"Pacific/Majuro",
    "Makassar":"Asia/Makassar",
    "Makhachkala":"Europe/Moscow",
    "Makiyivka":"Europe/Zaporozhye",
    "Malabo":"Africa/Malabo",
    "Malaga":"Europe/Madrid",
    "Malang":"Asia/Jakarta",
    "Malatya":"Europe/Istanbul",
    "Malawi":"Africa/Blantyre",
    "Malaysia":"Asia/Kuching",
    "Maldives":"Indian/Maldives",
    "Male":"Indian/Maldives",
    "Malegaon":"Asia/Kolkata",
    "Mali":"Africa/Bamako",
    "Malta":"Europe/Malta",
    "Mamoudzou":"Indian/Mayotte",
    "Mamuju":"Asia/Makassar",
    "Manado":"Asia/Makassar",
    "Managua":"America/Managua",
    "Manama":"Asia/Bahrain",
    "Manaus":"America/Manaus",
    "Mandalay":"Asia/Rangoon",
    "Mangalore":"Asia/Kolkata",
    "Manila":"Asia/Manila",
    "Mansilingan":"Asia/Manila",
    "Maputo":"Africa/Maputo",
    "Mar del Plata":"America/Argentina/Buenos_Aires",
    "Maracaibo":"America/Caracas",
    "Mariupol'":"Europe/Zaporozhye",
    "Marrakech":"Africa/Casablanca",
    "Marseille":"Europe/Paris",
    "Marshall Islands":"Pacific/Kwajalein",
    "Martinique":"America/Martinique",
    "Maryland":"America/New_York",
    "Maseru":"Africa/Maseru",
    "Mashhad":"Asia/Tehran",
    "Masina":"Africa/Kinshasa",
    "Massachusetts":"America/New_York",
    "Matamoros":"America/Monterrey",
    "Matola":"Africa/Maputo",
    "Matsudo":"Asia/Tokyo",
    "Maturin":"America/Caracas",
    "Maua":"America/Sao_Paulo",
    "Mauritania":"Africa/Nouakchott",
    "Mauritius":"Indian/Mauritius",
    "Mawlamyine":"Asia/Rangoon",
    "Mayotte":"Indian/Mayotte",
    "Mbabane":"Africa/Mbabane",
    "Mbuji-Mayi":"Africa/Lubumbashi",
    "Mecca":"Asia/Riyadh",
    "Medan":"Asia/Jakarta",
    "Medellin":"America/Bogota",
    "Medina":"Asia/Riyadh",
    "Meerut":"Asia/Kolkata",
    "Meknes":"Africa/Casablanca",
    "Melbourne":"Australia/Melbourne",
    "Melekeok":"Pacific/Palau",
    "Memphis":"America/Chicago",
    "Mendoza":"America/Argentina/Mendoza",
    "Mercin":"Europe/Istanbul",
    "Merida":"America/Merida",
    "Mesa":"America/Phoenix",
    "Mexicali":"America/Tijuana",
    "Mexico City":"America/Mexico_City",
    "Miami":"America/New_York",
    "Michigan":"America/Detroit",
    "Milano":"Europe/Rome",
    "Milwaukee":"America/Chicago",
    "Minneapolis":"America/Chicago",
    "Minnesota":"America/Chicago",
    "Minsk":"Europe/Minsk",
    "Misratah":"Africa/Tripoli",
    "Mississippi":"America/Chicago",
    "Missouri":"America/Chicago",
    "Mixco":"America/Guatemala",
    "Mogadishu":"Africa/Mogadishu",
    "Moldova":"Europe/Chisinau",
    "Mombasa":"Africa/Nairobi",
    "Monaco":"Europe/Monaco",
    "Mongolia":"Asia/Ulaanbaatar",
    "Monrovia":"Africa/Monrovia",
    "Montana":"America/Denver",
    "Montenegro":"Europe/Podgorica",
    "Monterrey":"America/Monterrey",
    "Montevideo":"America/Montevideo",
    "Montreal":"America/Montreal",
    "Montserrat":"America/Montserrat",
    "Moradabad":"Asia/Kolkata",
    "Morelia":"America/Mexico_City",
    "Morocco":"Africa/Casablanca",
    "Moroni":"Indian/Comoro",
    "Moscow":"Europe/Moscow",
    "Mosul":"Asia/Baghdad",
    "Mountain Time (MT)":"America/Denver",
    "Mozambique":"Africa/Maputo",
    "Muang Phonsavan":"Asia/Vientiane",
    "Mudanjiang":"Asia/Harbin",
    "Muenchen":"Europe/Berlin",
    "Multan":"Asia/Karachi",
    "Mumbai":"Asia/Kolkata",
    "Murcia":"Europe/Madrid",
    "Muscat":"Asia/Muscat",
    "Mwanza":"Africa/Dar_es_Salaam",
    "Myanmar":"Asia/Rangoon",
    "Mykolayiv":"Europe/Zaporozhye",
    "Mysore":"Asia/Kolkata",
    "N'Djamena":"Africa/Ndjamena",
    "Naberezhnyye Chelny":"Europe/Moscow",
    "Nagasaki":"Asia/Tokyo",
    "Nagoya":"Asia/Tokyo",
    "Nagpur":"Asia/Kolkata",
    "Nairobi":"Africa/Nairobi",
    "Namangan":"Asia/Tashkent",
    "Namibia":"Africa/Windhoek",
    "Namp'o":"Asia/Pyongyang",
    "Nampula":"Africa/Maputo",
    "Nanchang":"Asia/Shanghai",
    "Nanchong":"Asia/Chongqing",
    "Nangi":"Asia/Kolkata",
    "Nanjing":"Asia/Shanghai",
    "Nanning":"Asia/Chongqing",
    "Nantong":"Asia/Shanghai",
    "Napoli":"Europe/Rome",
    "Nashville":"America/Chicago",
    "Nasik":"Asia/Kolkata",
    "Nassau":"America/Nassau",
    "Natal":"America/Fortaleza",
    "Naucalpan de Juarez":"America/Mexico_City",
    "Nauru":"Pacific/Nauru",
    "Nay Pyi Taw":"Asia/Rangoon",
    "Ndola":"Africa/Lusaka",
    "Nebraska - Lincoln":"America/Chicago",
    "Nebraska - Omaha":"America/Chicago",
    "Neijiang":"Asia/Chongqing",
    "Nellore":"Asia/Kolkata",
    "Nepal":"Asia/Kathmandu",
    "Nerima":"Asia/Tokyo",
    "Netherlands":"Europe/Amsterdam",
    "Netherlands Antilles":"America/Curacao",
    "Nevada":"America/Los_Angeles",
    "New Caledonia":"Pacific/Noumea",
    "New Delhi":"Asia/Kolkata",
    "New Hampshire":"America/New_York",
    "New Jersey":"America/New_York",
    "New Kingston":"America/Jamaica",
    "New Mexico":"America/Denver",
    "New Orleans":"America/Chicago",
    "New South Memphis":"America/Chicago",
    "New York":"America/New_York",
    "New Zealand":"Pacific/Auckland",
    "Newark":"America/New_York",
    "Niamey":"Africa/Niamey",
    "Nicaragua":"America/Managua",
    "Nicosia":"Asia/Nicosia",
    "Niger":"Africa/Niamey",
    "Nigeria":"Africa/Lagos",
    "Niigata":"Asia/Tokyo",
    "Ningbo":"Asia/Shanghai",
    "Nishinomiya":"Asia/Tokyo",
    "Niteroi":"America/Sao_Paulo",
    "Niue":"Pacific/Niue",
    "Nizhniy Novgorod":"Europe/Moscow",
    "Nizhniy Tagil":"Asia/Yekaterinburg",
    "Norfolk Island":"Pacific/Norfolk",
    "North Carolina":"America/New_York",
    "North Dakota - Fargo":"America/Chicago",
    "North Korea":"Asia/Pyongyang",
    "North York":"America/Toronto",
    "Northern Mariana Islands":"Pacific/Saipan",
    "Norway":"Europe/Oslo",
    "Nouakchott":"Africa/Nouakchott",
    "Noumea":"Pacific/Noumea",
    "Nova Iguacu":"America/Sao_Paulo",
    "Novokuznetsk":"Asia/Krasnoyarsk",
    "Novosibirsk":"Asia/Novosibirsk",
    "Nuernberg":"Europe/Berlin",
    "Nuku`alofa":"Pacific/Tongatapu",
    "Nuuk":"America/Godthab",
    "Oakland":"America/Los_Angeles",
    "Odesa":"Europe/Simferopol",
    "Ohio":"America/New_York",
    "Oita":"Asia/Tokyo",
    "Okayama":"Asia/Tokyo",
    "Okene":"Africa/Lagos",
    "Oklahoma":"America/Chicago",
    "Oklahoma City":"America/Chicago",
    "Omaha":"America/Chicago",
    "Oman":"Asia/Muscat",
    "Omdurman":"Africa/Khartoum",
    "Omsk":"Asia/Omsk",
    "Onitsha":"Africa/Lagos",
    "Oran":"Africa/Algiers",
    "Oranjestad":"America/Aruba",
    "Oregon - Portland":"America/Los_Angeles",
    "Orenburg":"Asia/Yekaterinburg",
    "Orumiyeh":"Asia/Tehran",
    "Osaka":"Asia/Tokyo",
    "Osasco":"America/Sao_Paulo",
    "Oslo":"Europe/Oslo",
    "Ottawa":"America/Montreal",
    "Ouagadougou":"Africa/Ouagadougou",
    "Oujda":"Africa/Casablanca",
    "Owensboro":"America/Chicago",
    "Oyo":"Africa/Lagos",
    "PT (Pacific Time)":"America/Los_Angeles",
    "Pacific Time (PT)":"America/Los_Angeles",
    "Padang":"Asia/Jakarta",
    "Pago Pago":"Pacific/Pago_Pago",
    "Pakistan":"Asia/Karachi",
    "Palau":"Pacific/Palau",
    "Palembang":"Asia/Jakarta",
    "Palermo":"Europe/Rome",
    "Palestinian Territory":"Asia/Gaza",
    "Palikir":"Pacific/Ponape",
    "Palma":"Europe/Madrid",
    "Panama":"America/Panama",
    "Panihati":"Asia/Kolkata",
    "Panshan":"Asia/Harbin",
    "Panzhihua":"Asia/Chongqing",
    "Papeete":"Pacific/Tahiti",
    "Papua New Guinea":"Pacific/Port_Moresby",
    "Paraguay":"America/Asuncion",
    "Paramaribo":"America/Paramaribo",
    "Paris":"Europe/Paris",
    "Pasto":"America/Bogota",
    "Patna":"Asia/Kolkata",
    "Pennsylvania":"America/New_York",
    "Pensacola":"America/Chicago",
    "Penza":"Europe/Moscow",
    "Pereira":"America/Bogota",
    "Perm'":"Asia/Yekaterinburg",
    "Perth":"Australia/Perth",
    "Peru":"America/Lima",
    "Peshawar":"Asia/Karachi",
    "Petaling Jaya":"Asia/Kuala_Lumpur",
    "Philadelphia":"America/New_York",
    "Philippines":"Asia/Manila",
    "Phnom Penh":"Asia/Phnom_Penh",
    "Phoenix":"America/Phoenix",
    "Pietermaritzburg":"Africa/Johannesburg",
    "Pikine":"Africa/Dakar",
    "Pimpri":"Asia/Kolkata",
    "Pingdingshan":"Asia/Chongqing",
    "Pingxiang":"Asia/Chongqing",
    "Pitcairn":"Pacific/Pitcairn",
    "Plymouth":"America/Montserrat",
    "Podgorica":"Europe/Podgorica",
    "Pointe-Noire":"Africa/Brazzaville",
    "Poland":"Europe/Warsaw",
    "Ponce":"America/Puerto_Rico",
    "Pontianak":"Asia/Pontianak",
    "Port Elizabeth":"Africa/Johannesburg",
    "Port Harcourt":"Africa/Lagos",
    "Port Louis":"Indian/Mauritius",
    "Port Moresby":"Pacific/Port_Moresby",
    "Port Sudan":"Africa/Khartoum",
    "Port-Vila":"Pacific/Efate",
    "Port-au-Prince":"America/Port-au-Prince",
    "Port-of-Spain":"America/Port_of_Spain",
    "Porto Alegre":"America/Sao_Paulo",
    "Porto-Novo":"Africa/Porto-Novo",
    "Portugal":"Europe/Lisbon",
    "Poznan":"Europe/Warsaw",
    "Praha":"Europe/Prague",
    "Praia":"Atlantic/Cape_Verde",
    "Pretoria":"Africa/Johannesburg",
    "Pristina":"Europe/Belgrade",
    "Providence":"America/New_York",
    "Puch'on":"Asia/Seoul",
    "Puebla de Zaragoza":"America/Mexico_City",
    "Puerto Rico":"America/Puerto_Rico",
    "Pune":"Asia/Kolkata",
    "Pusan":"Asia/Seoul",
    "Putian":"Asia/Shanghai",
    "Pyongyang":"Asia/Pyongyang",
    "Qaraghandy":"Asia/Almaty",
    "Qatar":"Asia/Qatar",
    "Qingdao":"Asia/Shanghai",
    "Qinhuangdao":"Asia/Harbin",
    "Qiqihar":"Asia/Harbin",
    "Qom":"Asia/Tehran",
    "Quebec":"America/Montreal",
    "Queretaro":"America/Mexico_City",
    "Quetta":"Asia/Karachi",
    "Quilmes":"America/Argentina/Buenos_Aires",
    "Quilon":"Asia/Kolkata",
    "Quito":"America/Guayaquil",
    "Ra's Bayrut":"Asia/Beirut",
    "Rabat":"Africa/Casablanca",
    "Raipur":"Asia/Kolkata",
    "Rajkot":"Asia/Kolkata",
    "Rajshahi":"Asia/Dhaka",
    "Ranchi":"Asia/Kolkata",
    "Rangoon":"Asia/Rangoon",
    "Rapid City":"America/Denver",
    "Rasht":"Asia/Tehran",
    "Rawalpindi":"Asia/Karachi",
    "Recife":"America/Recife",
    "Resistencia":"America/Argentina/Cordoba",
    "Reunion":"Indian/Reunion",
    "Reykjavik":"Atlantic/Reykjavik",
    "Reynosa":"America/Monterrey",
    "Rhode Island":"America/New_York",
    "Ribeirao Preto":"America/Sao_Paulo",
    "Ribeirao das Neves":"America/Sao_Paulo",
    "Riga":"Europe/Riga",
    "Rio de Janeiro":"America/Sao_Paulo",
    "Riyadh":"Asia/Riyadh",
    "Road Town":"America/Tortola",
    "Roma":"Europe/Rome",
    "Romania":"Europe/Bucharest",
    "Rome":"Europe/Rome",
    "Rosario":"America/Argentina/Cordoba",
    "Roseau":"America/Dominica",
    "Rostov-na-Donu":"Europe/Moscow",
    "Rotterdam":"Europe/Amsterdam",
    "Rwanda":"Africa/Kigali",
    "Ryazan'":"Europe/Moscow",
    "Sacramento":"America/Los_Angeles",
    "Sagamihara":"Asia/Tokyo",
    "Saharanpur":"Asia/Kolkata",
    "Saint BarthÃ©lemy":"America/Guadeloupe",
    "Saint George's":"America/Grenada",
    "Saint Helena":"Atlantic/St_Helena",
    "Saint Helier":"Europe/Jersey",
    "Saint John's":"America/Antigua",
    "Saint Kitts and Nevis":"America/St_Kitts",
    "Saint Louis":"America/Chicago",
    "Saint Lucia":"America/St_Lucia",
    "Saint Martin":"America/Guadeloupe",
    "Saint Peter Port":"Europe/Guernsey",
    "Saint Petersburg":"Europe/Moscow",
    "Saint Pierre and Miquelon":"America/Miquelon",
    "Saint Vincent and the Grenadines":"America/St_Vincent",
    "Saint-Denis":"Indian/Reunion",
    "Saint-Pierre":"America/Miquelon",
    "Saitama":"Asia/Tokyo",
    "Sakai":"Asia/Tokyo",
    "Salem":"Asia/Kolkata",
    "Salt Lake City":"America/Denver",
    "Salta":"America/Argentina/Salta",
    "Saltillo":"America/Monterrey",
    "Salvador":"America/Bahia",
    "Samara":"Europe/Samara",
    "Samoa":"Pacific/Apia",
    "Samsun":"Europe/Istanbul",
    "Samut Prakan":"Asia/Bangkok",
    "San Antonio":"America/Chicago",
    "San Diego":"America/Los_Angeles",
    "San Francisco":"America/Los_Angeles",
    "San Jose":"America/Los_Angeles",
    "San Luis Potosi":"America/Mexico_City",
    "San Marino":"Europe/San_Marino",
    "San Miguel de Tucuman":"America/Argentina/Tucuman",
    "San Nicolas de los Garzas":"America/Monterrey",
    "San Pedro Sula":"America/Tegucigalpa",
    "San Salvador":"America/El_Salvador",
    "Sanaa":"Asia/Aden",
    "Sandakan":"Asia/Kuching",
    "Sanliurfa":"Europe/Istanbul",
    "Santa Cruz de la Sierra":"America/La_Paz",
    "Santa Fe de la Vera Cruz":"America/Argentina/Cordoba",
    "Santa Marta":"America/Bogota",
    "Santiago":"America/Santiago",
    "Santiago de Cuba":"America/Havana",
    "Santiago de los Caballeros":"America/Santo_Domingo",
    "Santo Andre":"America/Sao_Paulo",
    "Santo Domingo":"America/Santo_Domingo",
    "Santos":"America/Sao_Paulo",
    "Sao Bernardo do Campo":"America/Sao_Paulo",
    "Sao Joao de Meriti":"America/Sao_Paulo",
    "Sao Jose do Rio Preto":"America/Sao_Paulo",
    "Sao Jose dos Campos":"America/Sao_Paulo",
    "Sao Luis":"America/Fortaleza",
    "Sao Paulo":"America/Sao_Paulo",
    "Sao Tome":"Africa/Sao_Tome",
    "Sao Tome and Principe":"Africa/Sao_Tome",
    "Sapporo":"Asia/Tokyo",
    "Sarajevo":"Europe/Sarajevo",
    "Saratov":"Europe/Volgograd",
    "Sargodha":"Asia/Karachi",
    "Saudi Arabia":"Asia/Riyadh",
    "Seattle":"America/Los_Angeles",
    "Semarang":"Asia/Jakarta",
    "Sendai":"Asia/Tokyo",
    "Senegal":"Africa/Dakar",
    "Seoul":"Asia/Seoul",
    "Serbia":"Europe/Belgrade",
    "Seremban":"Asia/Kuala_Lumpur",
    "Serra":"America/Sao_Paulo",
    "Sevastopol'":"Europe/Simferopol",
    "Sevilla":"Europe/Madrid",
    "Seychelles":"Indian/Mahe",
    "Shah Alam":"Asia/Kuala_Lumpur",
    "Shanghai":"Asia/Shanghai",
    "Shantou":"Asia/Shanghai",
    "Shaoguan":"Asia/Chongqing",
    "Shaoxing":"Asia/Shanghai",
    "Sharjah":"Asia/Dubai",
    "Shashi":"Asia/Chongqing",
    "Sheffield":"Europe/London",
    "Shenyang":"Asia/Harbin",
    "Shenzhen":"Asia/Chongqing",
    "Shihezi":"Asia/Urumqi",
    "Shijiazhuang":"Asia/Shanghai",
    "Shiliguri":"Asia/Kolkata",
    "Shimminatocho":"Asia/Tokyo",
    "Shiraz":"Asia/Tehran",
    "Shivaji Nagar":"Asia/Kolkata",
    "Shizuoka":"Asia/Tokyo",
    "Shuangyashan":"Asia/Harbin",
    "Shymkent":"Asia/Qyzylorda",
    "Sialkot":"Asia/Karachi",
    "Sierra Leone":"Africa/Freetown",
    "Singapore":"Asia/Singapore",
    "Sioux Falls":"America/Chicago",
    "Siping":"Asia/Harbin",
    "Situbondo":"Asia/Jakarta",
    "Skopje":"Europe/Skopje",
    "Slovakia":"Europe/Bratislava",
    "Slovenia":"Europe/Ljubljana",
    "Sofia":"Europe/Sofia",
    "Sokoto":"Africa/Lagos",
    "Solapur":"Asia/Kolkata",
    "Solomon Islands":"Pacific/Guadalcanal",
    "Somalia":"Africa/Mogadishu",
    "Songnam":"Asia/Seoul",
    "Sorocaba":"America/Sao_Paulo",
    "South Africa":"Africa/Johannesburg",
    "South Boston":"America/New_York",
    "South Carolina":"America/New_York",
    "South Dakota - Rapid City":"America/Denver",
    "South Dakota - Sioux Falls":"America/Chicago",
    "South Georgia and the South Sandwich Islands":"Atlantic/South_Georgia",
    "South Korea":"Asia/Seoul",
    "Soweto":"Africa/Johannesburg",
    "Spain":"Europe/Madrid",
    "Sri Lanka":"Asia/Colombo",
    "Srinagar":"Asia/Kolkata",
    "Stanley":"Atlantic/Stanley",
    "Stockholm":"Europe/Stockholm",
    "Stuttgart":"Europe/Berlin",
    "Sucre":"America/La_Paz",
    "Sudan":"Africa/Khartoum",
    "Suez":"Africa/Cairo",
    "Sukkur":"Asia/Karachi",
    "Sultanah":"Asia/Riyadh",
    "Surabaya":"Asia/Jakarta",
    "Surakarta":"Asia/Jakarta",
    "Surat":"Asia/Kolkata",
    "Suriname":"America/Paramaribo",
    "Suva":"Pacific/Fiji",
    "Suwon":"Asia/Seoul",
    "Suzhou":"Asia/Shanghai",
    "Svalbard and Jan Mayen":"Arctic/Longyearbyen",
    "Swaziland":"Africa/Mbabane",
    "Sweden":"Europe/Stockholm",
    "Switzerland":"Europe/Zurich",
    "Sydney":"Australia/Sydney",
    "Syria":"Asia/Damascus",
    "Szczecin":"Europe/Warsaw",
    "T'ai-chung-shih":"Asia/Taipei",
    "Ta`izz":"Asia/Aden",
    "Tabriz":"Asia/Tehran",
    "Tabuk":"Asia/Riyadh",
    "Taegu":"Asia/Seoul",
    "Taejon":"Asia/Seoul",
    "Tai'an":"Asia/Shanghai",
    "Tainan City":"Asia/Taipei",
    "Taipei":"Asia/Taipei",
    "Taiwan":"Asia/Taipei",
    "Taiyuan":"Asia/Chongqing",
    "Taizhou":"Asia/Shanghai",
    "Tajikistan":"Asia/Dushanbe",
    "Tallinn":"Europe/Tallinn",
    "Tangerang":"Asia/Jakarta",
    "Tanggu":"Asia/Shanghai",
    "Tangier":"Africa/Casablanca",
    "Tangshan":"Asia/Harbin",
    "Tanjungkarang-Telukbetung":"Asia/Jakarta",
    "Tanta":"Africa/Cairo",
    "Tanzania":"Africa/Dar_es_Salaam",
    "Tashkent":"Asia/Tashkent",
    "Tbilisi":"Asia/Tbilisi",
    "Tegucigalpa":"America/Tegucigalpa",
    "Tehran":"Asia/Tehran",
    "Tel Aviv-Yafo":"Asia/Jerusalem",
    "Tembisa":"Africa/Johannesburg",
    "Teni":"Asia/Kolkata",
    "Tennessee - Knoxville":"America/New_York",
    "Tennessee - Memphis":"America/Chicago",
    "Tennessee - Nashville":"America/Chicago",
    "Teresina":"America/Fortaleza",
    "Texas - El Paso":"America/Denver",
    "Texas - Houston":"America/Chicago",
    "Thailand":"Asia/Bangkok",
    "Thane":"Asia/Kolkata",
    "Thanh pho Ho Chi Minh":"Asia/Ho_Chi_Minh",
    "The Valley":"America/Anguilla",
    "Thimphu":"Asia/Thimphu",
    "Thiruvananthapuram":"Asia/Kolkata",
    "Tianjin":"Asia/Shanghai",
    "Tijuana":"America/Tijuana",
    "Tirana":"Europe/Tirane",
    "Tiruchchirappalli":"Asia/Kolkata",
    "Tirunelveli":"Asia/Kolkata",
    "Tiruppur":"Asia/Kolkata",
    "Tlalnepantla":"America/Mexico_City",
    "Tlaquepaque":"America/Mexico_City",
    "Togo":"Africa/Lome",
    "Tokelau":"Pacific/Fakaofo",
    "Tokyo":"Asia/Tokyo",
    "Tol'yatti":"Europe/Samara",
    "Toluca":"America/Mexico_City",
    "Tomsk":"Asia/Krasnoyarsk",
    "Tonala":"America/Mexico_City",
    "Tonga":"Pacific/Tongatapu",
    "Torino":"Europe/Rome",
    "Toronto":"America/Toronto",
    "Torreon":"America/Monterrey",
    "Torshavn":"Atlantic/Faroe",
    "Toulouse":"Europe/Paris",
    "Toyohashi":"Asia/Tokyo",
    "Toyonaka":"Asia/Tokyo",
    "Trinidad and Tobago":"America/Port_of_Spain",
    "Tripoli":"Africa/Tripoli",
    "Trujillo":"America/Lima",
    "Tucson":"America/Phoenix",
    "Tula":"Europe/Moscow",
    "Tulsa":"America/Chicago",
    "Tunis":"Africa/Tunis",
    "Tunisia":"Africa/Tunis",
    "Turkey":"Europe/Istanbul",
    "Turkmenistan":"Asia/Ashgabat",
    "Turks and Caicos Islands":"America/Grand_Turk",
    "Tuvalu":"Pacific/Funafuti",
    "Tuxtla Gutierrez":"America/Mexico_City",
    "Tver'":"Europe/Moscow",
    "Tyumen'":"Asia/Yekaterinburg",
    "U.S. Virgin Islands":"America/St_Thomas",
    "Uberlandia":"America/Sao_Paulo",
    "Udaipur":"Asia/Kolkata",
    "Ufa":"Asia/Yekaterinburg",
    "Uganda":"Africa/Kampala",
    "Uijongbu":"Asia/Seoul",
    "Ujjain":"Asia/Kolkata",
    "Ukraine":"Europe/Kiev",
    "Ul'yanovsk":"Europe/Volgograd",
    "Ulaanbaatar":"Asia/Ulaanbaatar",
    "Ulhasnagar":"Asia/Kolkata",
    "Ulsan":"Asia/Seoul",
    "United Arab Emirates":"Asia/Dubai",
    "United Kingdom":"Europe/London",
    "Uruguay":"America/Montevideo",
    "Urumqi":"Asia/Urumqi",
    "Utah":"America/Denver",
    "Utsunomiya":"Asia/Tokyo",
    "Uzbekistan":"Asia/Samarkand",
    "Vadodara":"Asia/Kolkata",
    "Vaduz":"Europe/Vaduz",
    "Valletta":"Europe/Malta",
    "Van":"Europe/Istanbul",
    "Vancouver":"America/Vancouver",
    "Vanuatu":"Pacific/Efate",
    "Vatican":"Europe/Vatican",
    "Vatican City":"Europe/Vatican",
    "Venezuela":"America/Caracas",
    "Venice":"Europe/Rome",
    "Veracruz":"America/Mexico_City",
    "Vereeniging":"Africa/Johannesburg",
    "Vermont":"America/New_York",
    "Victoria":"Indian/Mahe",
    "Vienna":"Europe/Vienna",
    "Vientiane":"Asia/Vientiane",
    "Vietnam":"Asia/Ho_Chi_Minh",
    "Vijayawada":"Asia/Kolkata",
    "Vila Velha":"America/Sao_Paulo",
    "Villa Nueva":"America/Guatemala",
    "Vilnius":"Europe/Vilnius",
    "Virginia":"America/New_York",
    "Virginia Beach":"America/New_York",
    "Vishakhapatnam":"Asia/Kolkata",
    "Vladivostok":"Asia/Vladivostok",
    "Volgograd":"Europe/Volgograd",
    "Voronezh":"Europe/Moscow",
    "Wallis and Futuna":"Pacific/Wallis",
    "Warangal":"Asia/Kolkata",
    "Warri":"Africa/Lagos",
    "Warsaw":"Europe/Warsaw",
    "Washington":"America/New_York",
    "Washington - Seattle":"America/Los_Angeles",
    "Weifang":"Asia/Shanghai",
    "Welkom":"Africa/Johannesburg",
    "Wellington":"Pacific/Auckland",
    "Wenzhou":"Asia/Shanghai",
    "West Virginia":"America/New_York",
    "Western Sahara":"Africa/El_Aaiun",
    "Wichita":"America/Chicago",
    "Willemstad":"America/Curacao",
    "Wilmington":"America/New_York",
    "Windhoek":"Africa/Windhoek",
    "Winnipeg":"America/Winnipeg",
    "Wisconsin":"America/Chicago",
    "Wroclaw":"Europe/Warsaw",
    "Wuhan":"Asia/Shanghai",
    "Wuhu":"Asia/Shanghai",
    "Wuxi":"Asia/Shanghai",
    "Wyoming":"America/Denver",
    "Xi'an":"Asia/Chongqing",
    "Xiamen":"Asia/Shanghai",
    "Xiangfan":"Asia/Chongqing",
    "Xiangtan":"Asia/Chongqing",
    "Xianyang":"Asia/Chongqing",
    "Xingtai":"Asia/Shanghai",
    "Xining":"Asia/Chongqing",
    "Xinpu":"Asia/Shanghai",
    "Xinxiang":"Asia/Shanghai",
    "Xinyang":"Asia/Shanghai",
    "Xuanhua":"Asia/Harbin",
    "Xuchang":"Asia/Shanghai",
    "Xuzhou":"Asia/Shanghai",
    "Yamoussoukro":"Africa/Abidjan",
    "Yancheng":"Asia/Shanghai",
    "Yangjiang":"Asia/Chongqing",
    "Yangquan":"Asia/Shanghai",
    "Yangzhou":"Asia/Shanghai",
    "Yantai":"Asia/Shanghai",
    "Yaounde":"Africa/Douala",
    "Yaroslavl'":"Europe/Moscow",
    "Yazd":"Asia/Tehran",
    "Yekaterinburg":"Asia/Yekaterinburg",
    "Yemen":"Asia/Aden",
    "Yerevan":"Asia/Yerevan",
    "Yichang":"Asia/Chongqing",
    "Yinchuan":"Asia/Chongqing",
    "Yingkou":"Asia/Harbin",
    "Yogyakarta":"Asia/Jakarta",
    "Yokohama":"Asia/Tokyo",
    "Yokosuka":"Asia/Tokyo",
    "Yono":"Asia/Tokyo",
    "Yunfu":"Asia/Chongqing",
    "Zagreb":"Europe/Zagreb",
    "Zagreb - Centar":"Europe/Zagreb",
    "Zahedan":"Asia/Tehran",
    "Zambia":"Africa/Lusaka",
    "Zamboanga":"Asia/Manila",
    "Zanzibar":"Africa/Dar_es_Salaam",
    "Zapopan":"America/Mexico_City",
    "Zaporizhzhya":"Europe/Zaporozhye",
    "Zaragoza":"Europe/Madrid",
    "Zaria":"Africa/Lagos",
    "Zhangjiakou":"Asia/Harbin",
    "Zhangzhou":"Asia/Shanghai",
    "Zhanjiang":"Asia/Chongqing",
    "Zhengzhou":"Asia/Shanghai",
    "Zhenjiang":"Asia/Shanghai",
    "Zhoukou":"Asia/Shanghai",
    "Zhuhai":"Asia/Chongqing",
    "Zhumadian":"Asia/Shanghai",
    "Zhuzhou":"Asia/Chongqing",
    "Zibo":"Asia/Shanghai",
    "Zigong":"Asia/Chongqing",
    "Zimbabwe":"Africa/Harare",
    "Zunyi":"Asia/Chongqing",
    "`Adan":"Asia/Aden",
    "vina causino":"America/Santiago"
};

var olson = {"Africa/Abidjan":0,"Africa/Accra":0,"Africa/Addis_Ababa":10800,"Africa/Algiers":3600,"Africa/Asmara":10800,"Africa/Asmera":10800,"Africa/Bamako":0,"Africa/Bangui":3600,"Africa/Banjul":0,"Africa/Bissau":0,"Africa/Blantyre":7200,"Africa/Brazzaville":3600,"Africa/Bujumbura":7200,"Africa/Cairo":7200,"Africa/Casablanca":0,"Africa/Ceuta":3600,
"Africa/Conakry":0,"Africa/Dakar":0,"Africa/Dar_es_Salaam":10800,"Africa/Djibouti":10800,"Africa/Douala":3600,"Africa/El_Aaiun":0,"Africa/Freetown":0,"Africa/Gaborone":7200,"Africa/Harare":7200,"Africa/Johannesburg":7200,"Africa/Kampala":10800,"Africa/Khartoum":10800,"Africa/Kigali":7200,"Africa/Kinshasa":3600,"Africa/Lagos":3600,"Africa/Libreville":3600,
"Africa/Lome":0,"Africa/Luanda":3600,"Africa/Lubumbashi":7200,"Africa/Lusaka":7200,"Africa/Malabo":3600,"Africa/Maputo":7200,"Africa/Maseru":7200,"Africa/Mbabane":7200,"Africa/Mogadishu":10800,"Africa/Monrovia":0,"Africa/Nairobi":10800,"Africa/Ndjamena":3600,"Africa/Niamey":3600,"Africa/Nouakchott":0,"Africa/Ouagadougou":0,"Africa/Porto-Novo":3600,
"Africa/Sao_Tome":0,"Africa/Timbuktu":0,"Africa/Tripoli":7200,"Africa/Tunis":3600,"Africa/Windhoek":7200,"America/Adak":-36000,"America/Anchorage":-32400,"America/Anguilla":-14400,"America/Antigua":-14400,"America/Araguaina":-10800,"America/Argentina/Buenos_Aires":-10800,"America/Argentina/Catamarca":-10800,"America/Argentina/ComodRivadavia":-10800,
"America/Argentina/Cordoba":-10800,"America/Argentina/Jujuy":-10800,"America/Argentina/La_Rioja":-10800,"America/Argentina/Mendoza":-10800,"America/Argentina/Rio_Gallegos":-10800,"America/Argentina/Salta":-10800,"America/Argentina/San_Juan":-10800,"America/Argentina/San_Luis":-10800,"America/Argentina/Tucuman":-10800,"America/Argentina/Ushuaia":-10800,
"America/Aruba":-14400,"America/Asuncion":-10800,"America/Atikokan":-18000,"America/Atka":-36000,"America/Bahia":-10800,"America/Bahia_Banderas":-21600,"America/Barbados":-14400,"America/Belem":-10800,"America/Belize":-21600,"America/Blanc-Sablon":-14400,"America/Boa_Vista":-14400,"America/Bogota":-18000,"America/Boise":-25200,"America/Buenos_Aires":-10800,
"America/Cambridge_Bay":-25200,"America/Campo_Grande":-10800,"America/Cancun":-21600,"America/Caracas":-16200,"America/Catamarca":-10800,"America/Cayenne":-10800,"America/Cayman":-18000,"America/Chicago":-21600,"America/Chihuahua":-25200,"America/Coral_Harbour":-18000,"America/Cordoba":-10800,"America/Costa_Rica":-21600,"America/Cuiaba":-10800,
"America/Curacao":-14400,"America/Danmarkshavn":0,"America/Dawson":-28800,"America/Dawson_Creek":-25200,"America/Denver":-25200,"America/Detroit":-18000,"America/Dominica":-14400,"America/Edmonton":-25200,"America/Eirunepe":-14400,"America/El_Salvador":-21600,"America/Ensenada":-28800,"America/Fort_Wayne":-18000,"America/Fortaleza":-10800,
"America/Glace_Bay":-14400,"America/Godthab":-10800,"America/Goose_Bay":-14400,"America/Grand_Turk":-18000,"America/Grenada":-14400,"America/Guadeloupe":-14400,"America/Guatemala":-21600,"America/Guayaquil":-18000,"America/Guyana":-14400,"America/Halifax":-14400,"America/Havana":-18000,"America/Hermosillo":-25200,"America/Indiana/Indianapolis":-18000,
"America/Indiana/Knox":-21600,"America/Indiana/Marengo":-18000,"America/Indiana/Petersburg":-18000,"America/Indiana/Tell_City":-21600,"America/Indiana/Vevay":-18000,"America/Indiana/Vincennes":-18000,"America/Indiana/Winamac":-18000,"America/Indianapolis":-18000,"America/Inuvik":-25200,"America/Iqaluit":-18000,"America/Jamaica":-18000,"America/Jujuy":-10800,"America/Juneau":-32400,"America/Kentucky/Louisville":-18000,
"America/Kentucky/Monticello":-18000,"America/Knox_IN":-21600,"America/La_Paz":-14400,"America/Lima":-18000,"America/Los_Angeles":-28800,"America/Louisville":-18000,"America/Maceio":-10800,"America/Managua":-21600,"America/Manaus":-14400,"America/Marigot":-14400,"America/Martinique":-14400,"America/Matamoros":-21600,"America/Mazatlan":-25200,"America/Mendoza":-10800,"America/Menominee":-21600,"America/Merida":-21600,"America/Mexico_City":-21600,"America/Miquelon":-10800,"America/Moncton":-14400,"America/Monterrey":-21600,"America/Montevideo":-7200,"America/Montreal":-18000,"America/Montserrat":-14400,"America/Nassau":-18000,"America/New_York":-18000,"America/Nipigon":-18000,"America/Nome":-32400,"America/Noronha":-7200,"America/North_Dakota/Center":-21600,"America/North_Dakota/New_Salem":-21600,"America/Ojinaga":-25200,"America/Panama":-18000,"America/Pangnirtung":-18000,"America/Paramaribo":-10800,"America/Phoenix":-25200,"America/Port-au-Prince":-18000,"America/Port_of_Spain":-14400,"America/Porto_Acre":-14400,"America/Porto_Velho":-14400,"America/Puerto_Rico":-14400,"America/Rainy_River":-21600,"America/Rankin_Inlet":-21600,"America/Recife":-10800,"America/Regina":-21600,"America/Resolute":-18000,"America/Rio_Branco":-14400,"America/Rosario":-10800,"America/Santa_Isabel":-28800,"America/Santarem":-10800,"America/Santiago":-10800,"America/Santo_Domingo":-14400,"America/Sao_Paulo":-7200,"America/Scoresbysund":-3600,"America/Shiprock":-25200,"America/St_Barthelemy":-14400,"America/St_Johns":-12600,"America/St_Kitts":-14400,"America/St_Lucia":-14400,"America/St_Thomas":-14400,"America/St_Vincent":-14400,"America/Swift_Current":-21600,"America/Tegucigalpa":-21600,"America/Thule":-14400,"America/Thunder_Bay":-18000,"America/Tijuana":-28800,"America/Toronto":-18000,"America/Tortola":-14400,"America/Vancouver":-28800,"America/Virgin":-14400,"America/Whitehorse":-28800,"America/Winnipeg":-21600,"America/Yakutat":-32400,"America/Yellowknife":-25200,"Antarctica/Casey":28800,"Antarctica/Davis":25200,"Antarctica/DumontDUrville":36000,"Antarctica/Macquarie":39600,"Antarctica/Mawson":18000,"Antarctica/McMurdo":46800,"Antarctica/Palmer":-10800,"Antarctica/Rothera":-10800,"Antarctica/South_Pole":46800,"Antarctica/Syowa":10800,"Antarctica/Vostok":21600,"Arctic/Longyearbyen":3600,"Asia/Aden":10800,"Asia/Almaty":21600,"Asia/Amman":7200,"Asia/Anadyr":39600,"Asia/Aqtau":18000,"Asia/Aqtobe":18000,"Asia/Ashgabat":18000,"Asia/Ashkhabad":18000,"Asia/Baghdad":10800,"Asia/Bahrain":10800,"Asia/Baku":14400,"Asia/Bangkok":25200,"Asia/Beirut":7200,"Asia/Bishkek":21600,"Asia/Brunei":28800,"Asia/Calcutta":19800,"Asia/Choibalsan":28800,"Asia/Chongqing":28800,"Asia/Chungking":28800,"Asia/Colombo":19800,"Asia/Dacca":21600,"Asia/Damascus":7200,"Asia/Dhaka":21600,"Asia/Dili":32400,"Asia/Dubai":14400,"Asia/Dushanbe":18000,"Asia/Gaza":7200,"Asia/Harbin":28800,"Asia/Ho_Chi_Minh":25200,"Asia/Hong_Kong":28800,"Asia/Hovd":25200,"Asia/Irkutsk":28800,"Asia/Istanbul":7200,"Asia/Jakarta":25200,"Asia/Jayapura":32400,"Asia/Jerusalem":7200,"Asia/Kabul":16200,"Asia/Kamchatka":39600,"Asia/Karachi":18000,"Asia/Kashgar":28800,"Asia/Kathmandu":20700,"Asia/Katmandu":20700,"Asia/Kolkata":19800,"Asia/Krasnoyarsk":25200,"Asia/Kuala_Lumpur":28800,"Asia/Kuching":28800,"Asia/Kuwait":10800,"Asia/Macao":28800,"Asia/Macau":28800,"Asia/Magadan":39600,"Asia/Makassar":28800,"Asia/Manila":28800,"Asia/Muscat":14400,"Asia/Nicosia":7200,"Asia/Novokuznetsk":21600,"Asia/Novosibirsk":21600,"Asia/Omsk":21600,"Asia/Oral":18000,"Asia/Phnom_Penh":25200,"Asia/Pontianak":25200,"Asia/Pyongyang":32400,"Asia/Qatar":10800,"Asia/Qyzylorda":21600,"Asia/Rangoon":23400,"Asia/Riyadh":10800,"Asia/Saigon":25200,"Asia/Sakhalin":36000,"Asia/Samarkand":18000,"Asia/Seoul":32400,"Asia/Shanghai":28800,"Asia/Singapore":28800,"Asia/Taipei":28800,"Asia/Tashkent":18000,"Asia/Tbilisi":14400,"Asia/Tehran":12600,"Asia/Tel_Aviv":7200,"Asia/Thimbu":21600,"Asia/Thimphu":21600,"Asia/Tokyo":32400,"Asia/Ujung_Pandang":28800,"Asia/Ulaanbaatar":28800,"Asia/Ulan_Bator":28800,"Asia/Urumqi":28800,"Asia/Vientiane":25200,"Asia/Vladivostok":36000,"Asia/Yakutsk":32400,"Asia/Yekaterinburg":18000,"Asia/Yerevan":14400,"Atlantic/Azores":-3600,"Atlantic/Bermuda":-14400,"Atlantic/Canary":0,"Atlantic/Cape_Verde":-3600,"Atlantic/Faeroe":0,"Atlantic/Faroe":0,"Atlantic/Jan_Mayen":3600,"Atlantic/Madeira":0,"Atlantic/Reykjavik":0,"Atlantic/South_Georgia":-7200,"Atlantic/St_Helena":0,"Atlantic/Stanley":-10800,"Australia/ACT":39600,"Australia/Adelaide":37800,"Australia/Brisbane":36000,"Australia/Broken_Hill":37800,"Australia/Canberra":39600,"Australia/Currie":39600,"Australia/Darwin":34200,"Australia/Eucla":31500,"Australia/Hobart":39600,"Australia/LHI":39600,"Australia/Lindeman":36000,"Australia/Lord_Howe":39600,"Australia/Melbourne":39600,"Australia/NSW":39600,"Australia/North":34200,"Australia/Perth":28800,"Australia/Queensland":36000,"Australia/South":37800,"Australia/Sydney":39600,"Australia/Tasmania":39600,"Australia/Victoria":39600,"Australia/West":28800,"Australia/Yancowinna":37800,"Brazil/Acre":-14400,"Brazil/DeNoronha":-7200,"Brazil/East":-7200,"Brazil/West":-14400,"CET":3600,"CST6CDT":-21600,"Canada/Atlantic":-14400,"Canada/Central":-21600,"Canada/East-Saskatchewan":-21600,"Canada/Eastern":-18000,"Canada/Mountain":-25200,"Canada/Newfoundland":-12600,"Canada/Pacific":-28800,"Canada/Saskatchewan":-21600,"Canada/Yukon":-28800,"Chile/Continental":-10800,"Chile/EasterIsland":-18000,"Cuba":-18000,"EET":7200,"EST":-18000,"EST5EDT":-18000,"Egypt":7200,"Eire":0,"Etc/GMT":0,"Etc/GMT+0":0,"Etc/GMT+1":-3600,"Etc/GMT+10":-36000,"Etc/GMT+11":-39600,"Etc/GMT+12":-43200,"Etc/GMT+2":-7200,"Etc/GMT+3":-10800,"Etc/GMT+4":-14400,"Etc/GMT+5":-18000,"Etc/GMT+6":-21600,"Etc/GMT+7":-25200,"Etc/GMT+8":-28800,"Etc/GMT+9":-32400,"Etc/GMT-0":0,"Etc/GMT-1":3600,"Etc/GMT-10":36000,"Etc/GMT-11":39600,"Etc/GMT-12":43200,"Etc/GMT-13":46800,"Etc/GMT-14":50400,"Etc/GMT-2":7200,"Etc/GMT-3":10800,"Etc/GMT-4":14400,"Etc/GMT-5":18000,"Etc/GMT-6":21600,"Etc/GMT-7":25200,"Etc/GMT-8":28800,"Etc/GMT-9":32400,"Etc/GMT0":0,"Etc/Greenwich":0,"Etc/UCT":0,"Etc/UTC":0,"Etc/Universal":0,"Etc/Zulu":0,"Europe/Amsterdam":3600,"Europe/Andorra":3600,"Europe/Athens":7200,"Europe/Belfast":0,"Europe/Belgrade":3600,"Europe/Berlin":3600,"Europe/Bratislava":3600,"Europe/Brussels":3600,"Europe/Bucharest":7200,"Europe/Budapest":3600,"Europe/Chisinau":7200,"Europe/Copenhagen":3600,"Europe/Dublin":0,"Europe/Gibraltar":3600,"Europe/Guernsey":0,"Europe/Helsinki":7200,"Europe/Isle_of_Man":0,"Europe/Istanbul":7200,"Europe/Jersey":0,"Europe/Kaliningrad":7200,"Europe/Kiev":7200,"Europe/Lisbon":0,"Europe/Ljubljana":3600,"Europe/London":0,"Europe/Luxembourg":3600,"Europe/Madrid":3600,"Europe/Malta":3600,"Europe/Mariehamn":7200,"Europe/Minsk":7200,"Europe/Monaco":3600,"Europe/Moscow":10800,"Europe/Nicosia":7200,"Europe/Oslo":3600,"Europe/Paris":3600,"Europe/Podgorica":3600,"Europe/Prague":3600,"Europe/Riga":7200,"Europe/Rome":3600,"Europe/Samara":10800,"Europe/San_Marino":3600,"Europe/Sarajevo":3600,"Europe/Simferopol":7200,"Europe/Skopje":3600,"Europe/Sofia":7200,"Europe/Stockholm":3600,"Europe/Tallinn":7200,"Europe/Tirane":3600,"Europe/Tiraspol":7200,"Europe/Uzhgorod":7200,"Europe/Vaduz":3600,"Europe/Vatican":3600,"Europe/Vienna":3600,"Europe/Vilnius":7200,"Europe/Volgograd":10800,"Europe/Warsaw":3600,"Europe/Zagreb":3600,"Europe/Zaporozhye":7200,"Europe/Zurich":3600,"GB":0,"GB-Eire":0,"GMT":0,"GMT+0":0,"GMT-0":0,"GMT0":0,"Greenwich":0,"HST":-36000,"Hongkong":28800,"Iceland":0,"Indian/Antananarivo":10800,"Indian/Chagos":21600,"Indian/Christmas":25200,"Indian/Cocos":23400,"Indian/Comoro":10800,"Indian/Kerguelen":18000,"Indian/Mahe":14400,"Indian/Maldives":18000,"Indian/Mauritius":14400,"Indian/Mayotte":10800,"Indian/Reunion":14400,"Iran":12600,"Israel":7200,"Jamaica":-18000,"Japan":32400,"Kwajalein":43200,"Libya":7200,"MET":3600,"MST":-25200,"MST7MDT":-25200,"Mexico/BajaNorte":-28800,"Mexico/BajaSur":-25200,"Mexico/General":-21600,"NZ":46800,"NZ-CHAT":49500,"Navajo":-25200,"PRC":28800,"PST8PDT":-28800,"Pacific/Apia":-36000,"Pacific/Auckland":46800,"Pacific/Chatham":49500,"Pacific/Chuuk":36000,"Pacific/Easter":-18000,"Pacific/Efate":39600,"Pacific/Enderbury":46800,"Pacific/Fakaofo":-36000,"Pacific/Fiji":46800,"Pacific/Funafuti":43200,"Pacific/Galapagos":-21600,"Pacific/Gambier":-32400,"Pacific/Guadalcanal":39600,"Pacific/Guam":36000,"Pacific/Honolulu":-36000,"Pacific/Johnston":-36000,"Pacific/Kiritimati":50400,"Pacific/Kosrae":39600,"Pacific/Kwajalein":43200,"Pacific/Majuro":43200,"Pacific/Marquesas":-34200,"Pacific/Midway":-39600,"Pacific/Nauru":43200,"Pacific/Niue":-39600,"Pacific/Norfolk":41400,"Pacific/Noumea":39600,"Pacific/Pago_Pago":-39600,"Pacific/Palau":32400,"Pacific/Pitcairn":-28800,"Pacific/Pohnpei":39600,"Pacific/Ponape":39600,"Pacific/Port_Moresby":36000,"Pacific/Rarotonga":-36000,"Pacific/Saipan":36000,"Pacific/Samoa":-39600,"Pacific/Tahiti":-36000,"Pacific/Tarawa":43200,"Pacific/Tongatapu":46800,"Pacific/Truk":36000,"Pacific/Wake":43200,"Pacific/Wallis":43200,"Pacific/Yap":36000,"Poland":3600,"Portugal":0,"ROC":28800,"ROK":32400,"Singapore":28800,"Turkey":7200,"UCT":0,"US/Alaska":-32400,"US/Aleutian":-36000,"US/Arizona":-25200,"US/Central":-21600,"US/East-Indiana":-18000,"US/Eastern":-18000,"US/Hawaii":-36000,"US/Indiana-Starke":-21600,"US/Michigan":-18000,"US/Mountain":-25200,"US/Pacific":-28800,"US/Pacific-New":-28800,"US/Samoa":-39600,"UTC":0,"Universal":0,"W-SU":10800,"WET":0,"Zulu":0};

var gmts = {"GMT":0.0,
"GMT-14":-50400.0,
"GMT-13":-46800.0,
"GMT-12":-43200.0,
"GMT-11":-39600.0,
"GMT-10":-36000.0,
"GMT-9":-32400.0,
"GMT-8":-28800.0,
"GMT-7":-25200.0,
"GMT-6":-21600.0,
"GMT-5":-18000.0,
"GMT-4":-14400.0,
"GMT-3":-10800.0,
"GMT-2":-7200.0,
"GMT-1":-3600.0,
"GMT+0":0.0,
"GMT+1":3600.0,
"GMT+2":7200.0,
"GMT+3":10800.0,
"GMT+4":14400.0,
"GMT+5":18000.0,
"GMT+6":21600.0,
"GMT+7":25200.0,
"GMT+8":28800.0,
"GMT+9":32400.0,
"GMT+10":36000.0,
"GMT+11":39600.0,
"GMT+12":43200.0,
"GMT+13":46800.0,
"GMT+14":50400.0};
  var tznames = {"CEDT (Central European Daylight Time)":7200.0,
"Central European Daylight Time (CEDT)":7200.0,
"CEST (Central European Summer Time)":7200.0,
"Central European Summer Time (CEST)":7200.0,
"EDT (Eastern Daylight Time)":-14400.0,
"Eastern Daylight Time (EDT)":-14400.0,
"EST (Eastern Standard Time)":-18000.0,
"Eastern Standard Time (EST)":-18000.0,
"PDT (Pacific Daylight Time)":-25200.0,
"Pacific Daylight Time (PDT)":-25200.0,
"PST (Pacific Standard Time)":-28800.0,
"Pacific Standard Time (PST)":-28800.0,
"MDT (Mountain Daylight Time)":-21600.0,
"Mountain Daylight Time (MDT)":-21600.0,
"MST (Mountain Standard Time)":-25200.0,
"Mountain Standard Time (MST)":-25200.0,
"CDT (Central Daylight Time)":-18000.0,
"Central Daylight Time (CDT)":-18000.0,
"CST (Central Standard Time)":-21600.0,
"Central Standard Time (CST)":-21600.0,
"A (Alpha Time Zone)":3600.0,
"Alpha Time Zone (A)":3600.0,
"ACDT (Australian Central Daylight Time)":37800.0,
"Australian Central Daylight Time (ACDT)":37800.0,
"ACST (Australian Central Standard Time)":34200.0,
"Australian Central Standard Time (ACST)":34200.0,
"ADT (Atlantic Daylight Time)":-10800.0,
"Atlantic Daylight Time (ADT)":-10800.0,
"AEDT (Australian Eastern Daylight Time)":39600.0,
"Australian Eastern Daylight Time (AEDT)":39600.0,
"AEST (Australian Eastern Standard Time)":36000.0,
"Australian Eastern Standard Time (AEST)":36000.0,
"AKDT (Alaska Daylight Time)":-28800.0,
"Alaska Daylight Time (AKDT)":-28800.0,
"AKST (Alaska Standard Time)":-32400.0,
"Alaska Standard Time (AKST)":-32400.0,
"AST (Atlantic Standard Time)":-14400.0,
"Atlantic Standard Time (AST)":-14400.0,
"AWDT (Australian Western Daylight Time)":32400.0,
"Australian Western Daylight Time (AWDT)":32400.0,
"AWST (Australian Western Standard Time)":28800.0,
"Australian Western Standard Time (AWST)":28800.0,
"B (Bravo Time Zone)":7200.0,
"Bravo Time Zone (B)":7200.0,
"BST (British Summer Time)":3600.0,
"British Summer Time (BST)":3600.0,
"C (Charlie Time Zone)":10800.0,
"Charlie Time Zone (C)":10800.0,
"CET (Central European Time)":3600.0,
"Central European Time (CET)":3600.0,
"CXT (Christmas Island Time)":25200.0,
"Christmas Island Time (CXT)":25200.0,
"D (Delta Time Zone)":14400.0,
"Delta Time Zone (D)":14400.0,
"E (Echo Time Zone)":18000.0,
"Echo Time Zone (E)":18000.0,
"EEDT (Eastern European Daylight Time)":10800.0,
"Eastern European Daylight Time (EEDT)":10800.0,
"EEST (Eastern European Summer Time)":10800.0,
"Eastern European Summer Time (EEST)":10800.0,
"EET (Eastern European Time)":7200.0,
"Eastern European Time (EET)":7200.0,
"F (Foxtrot Time Zone)":21600.0,
"Foxtrot Time Zone (F)":21600.0,
"G (Golf Time Zone)":25200.0,
"Golf Time Zone (G)":25200.0,
"GMT (Greenwich Mean Time)":0.0,
"Greenwich Mean Time (GMT)":0.0,
"H (Hotel Time Zone)":28800.0,
"Hotel Time Zone (H)":28800.0,
"HADT (Hawaii-Aleutian Daylight Time)":-32400.0,
"Hawaii-Aleutian Daylight Time (HADT)":-32400.0,
"HAST (Hawaii-Aleutian Standard Time)":-36000.0,
"Hawaii-Aleutian Standard Time (HAST)":-36000.0,
"HST (Hawaii Standard Time)":-36000.0,
"Hawaii Standard Time (HST)":-36000.0,
"I (India Time Zone)":32400.0,
"India Time Zone (I)":32400.0,
"IST (Irish Summer Time)":3600.0,
"Irish Summer Time (IST)":3600.0,
"K (Kilo Time Zone)":36000.0,
"Kilo Time Zone (K)":36000.0,
"L (Lima Time Zone)":39600.0,
"Lima Time Zone (L)":39600.0,
"M (Mike Time Zone)":43200.0,
"Mike Time Zone (M)":43200.0,
"MESZ (MitteleuroŠische Sommerzeit)":7200.0,
"MitteleuroŠische Sommerzeit (MESZ)":7200.0,
"MEZ (MitteleuropŠische Zeit)":3600.0,
"MitteleuropŠische Zeit (MEZ)":3600.0,
"MSD (Moscow Daylight Time)":14400.0,
"Moscow Daylight Time (MSD)":14400.0,
"MSK (Moscow Standard Time)":10800.0,
"Moscow Standard Time (MSK)":10800.0,
"N (November Time Zone)":-3600.0,
"November Time Zone (N)":-3600.0,
"NDT (Newfoundland Daylight Time)":-9000.0,
"Newfoundland Daylight Time (NDT)":-9000.0,
"NFT (Norfolk (Island) Time)":41400.0,
"Norfolk (Island) Time (NFT)":41400.0,
"NST (Newfoundland Standard Time)":-12600.0,
"Newfoundland Standard Time (NST)":-12600.0,
"O (Oscar Time Zone)":-7200.0,
"Oscar Time Zone (O)":-7200.0,
"P (Papa Time Zone)":-10800.0,
"Papa Time Zone (P)":-10800.0,
"Q (Quebec Time Zone)":-14400.0,
"Quebec Time Zone (Q)":-14400.0,
"R (Romeo Time Zone)":-18000.0,
"Romeo Time Zone (R)":-18000.0,
"S (Sierra Time Zone)":-21600.0,
"Sierra Time Zone (S)":-21600.0,
"T (Tango Time Zone)":-25200.0,
"Tango Time Zone (T)":-25200.0,
"U (Uniform Time Zone)":-28800.0,
"Uniform Time Zone (U)":-28800.0,
"UTC (Coordinated Universal Time)":0.0,
"Coordinated Universal Time (UTC)":0.0,
"V (Victor Time Zone)":-32400.0,
"Victor Time Zone (V)":-32400.0,
"W (Whiskey Time Zone)":-36000.0,
"Whiskey Time Zone (W)":-36000.0,
"WDT (Western Daylight Time)":32400.0,
"Western Daylight Time (WDT)":32400.0,
"WEDT (Western European Daylight Time)":3600.0,
"Western European Daylight Time (WEDT)":3600.0,
"WEST (Western European Summer Time)":3600.0,
"Western European Summer Time (WEST)":3600.0,
"WET (Western European Time)":0.0,
"Western European Time (WET)":0.0,
"WST (Western Standard Time)":28800.0,
"Western Standard Time (WST)":28800.0,
"X (X-ray Time Zone)":-39600.0,
"X-ray Time Zone (X)":-39600.0,
"Y (Yankee Time Zone)":-43200.0,
"Yankee Time Zone (Y)":-43200.0,
"Z (Zulu Time Zone)":0.0,
"Zulu Time Zone (Z)":0.0};

function validate(value, max, min) {
    return value >= (min || 0) && value <= max;
}

function format(date) {
    var month = MONTHS_SHORT[date.getUTCMonth()];
    month = month[0].toUpperCase() + month.substr(1);
    var day   = date.getUTCDate();
    var hour  = date.getUTCHours();
    var min   = date.getUTCMinutes();
    var timeOfDay = "a.m.";
    var ret   = "";
    ret += month;
    ret += ". "
    ret += day;
    ret += ", ";
    if (hour > 12) {
        timeOfDay = "p.m.";
        hour -= 12;
    }
    ret += hour;
    ret += ":";
    if (min < 10) ret += "0";
    ret += min;
    ret += " ";
    ret += timeOfDay;
    return ret;
}

$(function() {
    var labels = [];
    for (var k in cities) {
        labels.push(k);
    }
	var now = new Date();
    var hours = now.getHours();
    var mins = now.getMinutes();
    var timeOfDay = "a.m.";
    if (hours > 12) {
        timeOfDay = "p.m.";
        hours -= 12;
    }
    if (mins < 10) mins = "0" + mins;
    var nowTime = hours + ":" + mins + " " + timeOfDay;
    function update() {
        var val = $("input#time").val().toLowerCase();
        if (val.match(TIME)) {
            var hours = parseInt(RegExp.$1, 10);
            var minutes = RegExp.$2 ? parseInt(RegExp.$2, 10) : 0;
            var hourOfDay = RegExp.$3.replace(/\./g, "");
            if (!validate(hours, 24) || !validate(minutes, 60))
                return;
            var date = new Date();
            if (hourOfDay == 'p' && hours < 12) {
                hours += 12;
            }
            date.setUTCHours(hours);
            date.setUTCMinutes(minutes);
            date.setUTCSeconds(0);
            date.setUTCMilliseconds(0);
            var place = cities[$("#in").val()];
            if (place) {
                $("#results h2 span").text($("#in").val());
                date.setMinutes(date.getMinutes() + olson[place]/60 + date.getTimezoneOffset());
                // TODO: Calculate relative to.
            } else {
                 $("#results h2 span").text("Local");
             }
            $("#results h2 strong").text(format(date));
        }
    }
    $("input#time")
        .focus()
        .val(nowTime)
        //.val(Date.today().toString())
        .keyup(function(e) {
            update();
        });
    $("input#from, input#in")
        .autocomplete({
			minLength: 3,
			source: labels,
			delay: 10,
			focus: function() {
				// prevent value inserted on focus
				return false;
			},
			close: function(event, ui) {
			    update();
		    },
			search: function(event, ui) {
			    update();
		    }
		});
    $("form").submit(function(f) {
        return false;
    });
});
